version: "3.4"
services:
  tensorflow-jupyter:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - PROXY=${HTTP_PROXY} 
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/tf/notebooks
